pre-commit:
  parallel: true
  commands:
    biome-check:
      run: pnpm run lint
    tsc-check:
      run: pnpm run tsc:check

pre-push:
  parallel: true
  commands:
    knip-check:
      run: pnpm run knip
